branches:
  only:
    - master
language: python
python:
    - 2.7
sudo: required
addons.apt.packages:
    - python-libvirt
    - python-yaml
    - make
before_install:
    - wget http://downloads.sourceforge.net/project/ssdeep/ssdeep-2.12/ssdeep-2.12.tar.gz
    - tar -zxvf ssdeep-2.12.tar.gz
    - cd ssdeep-2.12
    - ./configure && make
    - sudo make install
    - cd ..
    - sed -i 's/connection = .*/connection =/' conf/cuckoo.conf
install:
    - pip install -r requirements.txt
script:
    - python cuckoo.py --debug --test
    #- nosetests
